[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
license = "MIT or Apache-2.0"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
dirs = "6.0.0"
grass = "0.13.4"
gtk4-layer-shell = "0.5.0"
log = "0.4.27"
relm4 = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
simple_logger = "5.0.0"

[workspace.lints.clippy]
pedantic = "warn"
restriction = "allow" # maybe change to warn in the future
style = "warn"

[workspace.metadata]
crane.name = "dod-shell"
