[package]
name = "dod-shell"
license = "MIT or Apache-2.0"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
evalexpr = "12.0.2"
fuzzy-matcher = "0.3.7"
gtk4-layer-shell = "0.5.0"
relm4 = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
