[formatting]
indent_string = "  "
reorder_arrays = true
reorder_keys = true

[[rule]]
include = ["**/Cargo.toml", "deny.toml"]
keys = ["dependencies"]

[rule.formatting]
indent_string = "  "
reorder_arrays = true
reorder_keys = true
