# Sorts `Cargo.toml` dependencies. All other `.toml` files are formatted with the default config.
#
# https://taplo.tamasfe.dev/configuration/file.html#configuration-file

[formatting]
reorder_keys = false
reorder_arrays = true
indent_string = "  "

[[rule]]
include = ["**/Cargo.toml", "deny.toml"]
keys = ["dependencies"]

[rule.formatting]
reorder_keys = true
