[package]
name = "bar"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
dirs.workspace = true
gtk4-layer-shell.workspace = true
grass.workspace = true
log.workspace = true
relm4.workspace = true
serde.workspace = true
simple_logger.workspace = true
common.workspace = true

[lints]
workspace = true

[[bin]]
name = "dod-shell-bar"
path = "src/main.rs"
