---
name: Checks

"on":
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cache
        uses: actions/cache@v6
        with:
          # A list of files, directories, and
          # wildcard patterns to cache and restore
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - uses: cachix/install-nix-action@v31
      - name: Install dependencies
        run: nix profile install .#devShells.x86_64-linux.default

      - uses: j178/prek-action@v1
